# Generated by Django 5.1.5 on 2025-02-14 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_commentreview'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commentreview',
            name='created',
        ),
    ]
